### ISSUE TITLE
prob files in pred/pro/output/ are not created

### ISSUE THREAD

**Issue by SantiagoBarbarisi** [zhengshou/scnn#34]
Hi. I'm running the python demo file and i'm getting this error:

>extract frames starts
extract frames done in 10.043 s
init sliding window starts
init sliding window done in 0.0075 s
generate proposal list starts
generate proposal list done in 0.0074 s
run proposal network starts
run proposal network done in 0.0414 s
read proposal results starts
Traceback (most recent call last):
  File "run_demo.py", line 277, in <module>
    main()
  File "run_demo.py", line 95, in main
    prob = read_binary_blob(preddir+'pro/output/'+'{0:06}'.format(img_index+1)+'.prob')
  File "run_demo.py", line 240, in read_binary_blob
    f = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: 'pred/pro/output/000001.prob'

I've seen that it is because the `pred/pro/feature_extract.sh` file does not write the prob files, but I do not know how to solve it.

Any help will be appreciated

**Comment by WestBbbbrook** [comment]
hello,i meet the same problem ,have you solve it?  I change pred/pro/feature_extract.sh   file "C3D/1.0 "to "C3D/1.1 ", but it is not work,too.

**Comment by pyni** [comment]
汝等权值文件（SCNN_uniform16_binary_iter_30000）可能没有下载

**Comment by pyni** [comment]
将其放在正确的位置，则此问可迎刃而解矣

**Comment by 503004220** [comment]
> 将其放在正确的位置，则此问可迎刃而解矣

您好，我下载了这个文件，但是该问题还是没有解决。
请问这个文件应该放在什么地方，十分感谢！

**Comment by faith30** [comment]
> > 将其放在正确的位置，则此问可迎刃而解矣
> 
> 您好，我下载了这个文件，但是该问题还是没有解决。
> 请问这个文件应该放在什么地方，十分感谢！
You can read readme.md where need you download pre-trained models to ./models/ from Dropbox.

**Comment by wannibar** [comment]
> > > 将其放在正确的位置，则此问可迎刃而解矣
> > 
> > 
> > 您好，我下载了这个文件，但是该问题还是没有解决。
> > 请问这个文件应该放在什么地方，十分感谢！
> > You can read readme.md where need you download pre-trained models to ./models/ from Dropbox.

你解决了这个问题吗
